# file: deploy-nginx.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: configure-github-integration
spec:
  description: Click "Start Manual Execution" to the Right for Instructions
  application: &app-name armory-samples
  stages:
    - type: manualJudgment
      properties:
        name: Configure Github Integration
        refId: "1"
        failPipeline: true
        instructions: "Click Here ->  <a href=https://docs.armory.io/docs/armory-admin/artifacts-github-connect/>Configure Github</a><p><b>Watch Video and connect Github</b></p>"
