# file: deploy-nginx.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: configure-jenkins-integration
spec:
  description: Click "Start Manual Execution" to the Right for Instructions 
  application: &app-name armory-samples
  stages:
    - type: manualJudgment
      properties:
        name: Configure Jenkins Integration
        refId: "1"
        failPipeline: true
        instructions: "Click Here ->  <a href=ihttps://docs.armory.io/docs/armory-admin/jenkins-connect/>Configure Jenkins</a><p><b>Watch Video and Configure Jenkins</b></p>"
